FROM cpdc/mesos_executor
MAINTAINER Xiaotian Wu <xiaotian.wu@chinacache.com>
RUN git clone https://github.com/xiaotianwu/walle_monitor
RUN git clone https://github.com/xiaotianwu/kafka-python
RUN cd kafka-python&&python setup.py install
